### ISSUE TITLE
Not working on CE 5

### ISSUE THREAD

**Issue by jaxgti95** [hjgode/rdp-auto-login#1]
after configuring start-tsc and the RDP file to fit my environment, it still is not auto logging in. Just brings up remote desktop connection window and still requires username and password to be entered.

**Comment by hjgode** [comment]
a) this is a developer app. You may need to adjust the TSC window find function
b) runs fine for me on CE5 and CE6 devices, but may need to adjust the TSC find window function. Depends on the CE OEM build!
